// A Post Contains all of:
// - (Int) id
// - (String) post-name
// - (String) title
// - (Array) tags
// - (String/HTML) content

// "" : {
// 		title : "",
// 		description : "",
// 		tags : "",
// 		image : "",
// 	}

var content =
{
	"evertrue_amp" : {
		title : "EverTrue's Admin Management Portal",
		description : "EverTrue is a mobile platform developer, working to strengthen alumni relationships through the intersection of mobile applications, institutional knowledge, and social media such as LinkedIn. As a web development co-op at EverTrue, I worked alongside their product lead to prepare their Admin Management Portal. The Admin Management Portal, now refered to as ___, is a self-service tool for clients and admins. Leveraging Backbone and a PHP/MySQL powered internal API we brought this single page javascript web app from being used internally, to a client-facing self-service tool by the end of the summer. I held responsibility over a variety of features, such as the landing pages, authentication aesthetics and UX, maintaining the bootstrap based style guide, investiagting bug reoorts from client services, responsive design, and mangement page for sugguested updates. Working alongside, and coordinating prodic development betwee iOS, Android, Backend, and Client Services probided to be a rewarding part of the job.",
		tags : "Web Development, EverTrue, CSS3, HTML, Javascript, Backbone, jQuery, Bootstrap",
		image : "",
	},
	"linkedin-grader" : {
		title : "EverTrue's LinkedIn Grader",
		description : "Expanding off of a project that was born during a hackathon, I worked with EverTrue's data guy to prepare the LinkedIn greader for a public laucnh. Working off of an existing set of API calls to LinkedIn;s partner API, I worked to polish out the user experience, authenticate the user through LinkedIn account authentication, and publish/market the new web tool to generate more leads for potential clients.",
		tags : "Web Development, EverTrue, CSS3, HTML, Javascript, jQuery, AJAX, Hackathon, Bootstrap",
		image : "",
	},
	"eventler" : {
		title : "EverTrue's Eventler",
		description : "Eventler was a Javascript mini-tool for automating social event creation. Born during a hackathon, my team built a proof of concept tool showing that EventBrite Events, Facebook events, and mass e-mail marketing can be automated through a javascript web page calling various public APIs. Working alongside a backend specialist at EverTrue, I worked to write the javascript DOM maniputain, display options to the user, and execute API calls. Web Development, EverTrue, CSS3, HTML, Javascript, jQuery, Hackathon, Bootstrap",
		tags : "",
		image : "",
	},
	"fitbit-challenge" : {
		title : "EverTrue's FitBit Challenge",
		description : "EverTrue's 1,000,000 Step Challenge was a company wide initiative for everyone to maintain a 10,000 steps per day average. When the FitBit Dashboard didn't provide the level of competetiveness that we desired, it was decided that we would buid our own leaderboard and tracker website. The website accumulated data available through FitBit's API into a comparison of the entire team in releation to each other, complete with leaderboard, steps-to-go, average, tracking graphcs and 1v1 profile comparison statistics. The site was built supporting retina and fluid  layout to create a mobile-first experience. A JSON String of accumualted data was built through calling Fitbit's pyblic API, upon which my front-end code displayed and compared the page-specific data.",
		tags : "Web Development, EverTrue, CSS3, HTML, Javascript, jQuery, Hackathon",
		image : "",
	},
	"evertrue-email" : {
		title : "EverTrue E-mail Campaigns",
		description : "As we expirimented with the success and effectiveness of email campaigns and marketing, I created a number of e-mail templates from our designer's mockups. I then ported these templates to hubspot and mailchimp, where they would be used to send out to thousands of users. The largest challenge was writing, and testing HTML/CSS to be compatable amonng a wide variet of email clients, everything from iPhone 5 through Outlook, and Gmail had to be supported",
		tags : "EverTrue, CSS, HTML, email",
		image : "",
	},
	"texture-report" : {
		title : "Texture Report.com",
		description : "Texturetechnologies.com/blog, formally Texture Report.com, is a blog devoted to developments in the world of texture analysis testing. TextureReport.com is run by the team behind Texture Technologies, the North American reseller of the industry gold standard for testing texture analysis, the TA.XTPlus Texture Analyzer. Powered by wordpress, TextureReport.com is updated bi-monthly and highlights the most recent application studies, events and news in the Texture Testing community. Subscriptions work through Mailchimp, where subscribers can opt to recidve weekly updates generated by changes to the blog's RSS feed.",
		tags : "Web Development, Texture Technologies, Graphic Design, Web Design, CSS3, HTML, PHP, Wordpress, email",
		image : "",
	}
}








// texture-channel
// Texture Channel.com
// I have been working with Texture Technologies for a long time to produce tutorials of their products, and distribute the vides to ubscribed clients in a method that is both enjoyable for the user, and effective for Texture Technologies. Not only did I assist in filming, editing, and producing the video work, but I developed the website used to organize and stream the videos. The site itself pulls the video list and meta data from a MySQL table, and uses PHP Sessions and MySQL user records (md5'd of course) to authenticate user. Admins can create new user accounts and set an access expiration date for subscribers. The site uses AJAX to dynamically load the content and generate the ordered menu of available content at login.
// Web Development, Texture Technologies, Web Design, Graphic Design, Video, CSS3, HTML, Javascript, jQuery, AJAX, MySQL

// ttc-training-videos
// TA.XT Plus and Exponenet Training Videos
// Texture Technologies, Video, Premiere Pro, Tutorial
// As part of an ongoing video training series, I have done all the filming, setup, editing, hardware purchases, and publishing of the Texture Technoliges' training videos seen on texturechannel.com. These videos are part of a 50+ librabry of HD training videos, about the use of Texture Technologies' TA.XT Plus instruments and Exponentn software, all of which are avaibale to clients as a subsciption service.

// texturetechnologies
// TextureTechnologies.com
// I have worked with Texture Technologies for a few years, providing assistance with updating their website, filming training videos, and creating web solutions for content distribution. I have also collaborated to film tutorial videos for companies such as the Wheat Marketing Center, in Oregon, and to film the tutorials for their hardware and software. I constantly manage the content and design of their main website: TextureTechnologies.com
// Texture Technologies, Web Development, PHP, email

// quoth-the-raver
// QuoththeRaver.com
// Quoth the Raver is a music blog covering genres such as Electro, House, Drum & Bass, Dubstep, Glitch Hop, Trance. I designed there first blog last year, and after some discussion we finally decided to upgrade to a wordpress format. Check them out: QuoththeRaver.com.
// Web Development, Wordpress, PHP, Web Design

// clintvalentine
// ClintValentine.com
// __ Personal journal site for Clint Valentine, explorrer, adventurier, cyclist, scientist
// Web Development, Wordpress, PHP, Web Design

// firebrand-innovations
// FirebrandInnovations.com
// __ Company marketing site for small intellectual property development startup
// Web Development, Wordpress, Web Design, Bootstrap, Javascript

// markbuckler
// MarkBuckler.com
// __ Personal site for Mark Buckler: electrical engineer and founder of FirebrandInnocations
// Web Development, Javascript

// alexjohnson.io
// Web Development, Javascript

// logos
// Logo Designs
// [gallery]
// VideoConversation Design, NEU Transfer Club
// Graphic Design, Illustrator,

// print
// Print Designs
// [gallery]
// TTC Business Cards, TTC Print Ads,
// Graphic Design, Illustrator, Photoshop

// salem-state-web
// Salem State University Web Design
// During Summer 2010 through Spring 2011 I was hired by the IT department of Salem State University to develop and work on their web team. My focus was to propose designs and improvement to a number of tools used by the faculty and students. I used CSS, jQuery, and PHP to create mock-up designs, with the goal of emulating the final product. Here are 2 of my designs I proposed to replace their current user portal and internal tools.
// Programming
// Web Design, CSS3, Photoshop, HTML

// fmap
// Iterating over an FMap | FMap <K,V> Red/Black Tree
// A programming challenge: Design the data class and Iterator that handles iterating over a parameterized FMap. FMap is an immutable abstract data type with parameterized values that represent keys of type K to values of type V. In addition, design FMapIterator which implements Iterator and iterates over the keys of a given FMap. To download the source file (.java) right mouse click, and save the following link:Download Fmap and Iterator source file
// Java

// php-current
// Tutorial: Using PHP and CSS to highlight current page
// Here is an interesting little solution I came up with. When looking at a website navigation menu, what is the best way to change the CSS so that the current page is labeled? There is a million solutions. However, I am using this little PHP snippet to check the current pages file name, against the link name. In the isCurrent function, the method takes in a string(name of the link), compares it to the current page via the basename($_SERVER[PHP_SELF]) function. If true, the function returns "current" as the class name, or "link" for the non-current class name. Result: the CSS class names reflect the current page. Just add CSS styles for .current
// PHP, CSS3, Tutorial

// tetris
// Tetris in Scheme
// Here is a funny little assignment from freshman year. Programming Tetris in Racket using DrRacket (dialect of scheme). A partner and I wrote this code as one of the final projects in an Introduction to Programming course. It is basic tetris . It has the blocks, row removal, rotation, templates, and way too many check-expects (requirements of the assignment). Right & Left to move the block, A & S to rotate. Sorry about the indentation below. To download the source file (.rkt) right mouse click, and save the following link: Download Tetris in DrRacket
// Scheme,

// fire
// Fire Performance Photography
// [gallery]
// Photography, Photoshop

// landscape
// Landscape Photography
// [gallery]
// Photography

// macro
// Macro Photography
// [gallery]
// Photography

// quadcopter
// Quadcopter Project
// Ruby, C++

// quadcopter-docs
// Quadcopter Documentation
// Ruby

// brett-walfish
// Brett Walfish.com
// Brett Walfish is a professional violist and a graduate student of New England Conservatory. Brett Walfish is an avid chamber musician, having performed in the United States, Ireland, Italy and Israel. I designed and hosted a wordpress powered self-portfolio that he uses to publicize and share information about his passion and profession.
// Wordpress

// b2q-associates
// B2Q Associates.com
// B2Q Associates is a North Andover company specializing in a variety of engineering consulting services. Their licensed engineers, managers and designers provide services such as energy efficiency analysis, Energy Star certification, HVAC system design and building retro-commissioning. We were hired to face-lift their website. They wanted a modern, clean design that was easy to maintain without knowledge of HTML, PHP or other languages. I decided to use wordpress, and built a site that included purchasing stock photography, a featured-item slider for their services, a scrolling client logo list, and contact form.
// Wordpress

// wheat-marketing-center
// Wheat Marketing Center





// Salem State images
// more branding content?



// name:
// -snap
// -inline
// -design
// -dev



// misc designs:
// 4tkv


// affiliated projects:
// -kelsey norwood
// -brett walfish
// -robofo



// tutorials:
// -How to create an Action photoshop
// -
// -


// Favorite Android Apps:
// AirDroid
// Todo.txt
// Mint
// Dolphin Browser
// Easy Battery Saver
// GoSMS
// SpeedTest/Ping
// SleepTime
